import 'package:get/get_rx/src/rx_types/rx_types.dart';

var cruiseFormat = "".obs;
var cruiseDay = "".obs;
var cruiseShip = "".obs;
var cruiseRange = "".obs;
var cruiseCategory = "".obs;
var cruiseKey = "".obs;
var cruiseType = "".obs;
var cruiseCabine = "".obs;
var cruiseModality = "".obs;
var cruisePax = "".obs;
var cruiseTriple = "".obs;
var cruiseStarts = "".obs;
var cruiseEnds = "".obs;
var cruiseIslet = "".obs;
var cruiseItinerary = "".obs;
var cruisePort = "".obs;
var cruiseAnimal = "".obs;
var arrivalEdit = false.obs;
var departureEdit = false.obs;
var cruiseEdit = false.obs;